import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test Payment Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Thanks for your <a href="/checkout">Annual Subscription</a>
        </h1>

        <p className={styles.description}>
          Try the mock checkout application by clicking above link.
        </p>
      </main>
    </div>
  );
};

export default Home;
